0. Double the number of webservers

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,31 +1,29 @@
-#!/usr/bin/env bash
-# Configure your Nginx server so that /redirect_me is redirecting to another page
+#!/bin/bash
 
-apt-get update
-apt-get install -y nginx
-sudo ufw allow 'Nginx Http'
-mkdir -p /var/www/html
-touch /var/www/html/index.html
-echo "Hello World!" > /var/www/html/index.html
-touch /var/www/html/404.html
-echo "Ceci n'est pas une page" > /var/www/html/404.html
+# Update the package list and install Nginx
+sudo apt-get update
+sudo apt-get install nginx -y
 
-printf %s "server {
-     listen 80 default_server;
-     listen [::]:80 default_server;
-     add_header X-Served-By $HOSTNAME;
-     root /var/www/html;
-     index index.html index.htm;
-     
-     location /redirect_me {
-         return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
-     }
-     error_page 404 /404.html;
-     location /404 {
-         root /var/www/html;
-         internal;
-     }
-}
-" > /etc/nginx/sites-available/default
+# Configure Nginx to include the custom header
+echo 'server {
+    listen 80 default_server;
+    server_name _;
 
-service nginx restart
+    location / {
+        add_header X-Served-By $hostname;
+        # Your other location configurations here
+    }
+
+    # Your other server configurations here
+}' | sudo tee /etc/nginx/sites-available/default
+
+# Test the Nginx configuration
+sudo nginx -t
+
+# If the configuration test is successful, reload Nginx
+if [ $? -eq 0 ]; then
+    sudo systemctl reload nginx
+else
+    echo "Nginx configuration test failed. Please check your configuration."
+fi
+
